name: Deploy web folder to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Get repository
        uses: actions/checkout@v6

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload web folder
        uses: actions/upload-pages-artifact@v4
        with:
          path: './web'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
